"""initial

Revision ID: 47df0d412c7d
Revises: 
Create Date: 2026-05-20 19:03:10.842615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47df0d412c7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('begin_year', sa.Integer(), nullable=False),
        sa.Column('end_year', sa.Integer(), nullable=True),
        sa.Column('owner_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['countries.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
        sa.Column('num', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('reserve_url', sa.String(), nullable=True),
        sa.Column('image_file', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('quality', sa.String(), nullable=False),
        sa.Column('published', sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint('num')
    )
    op.create_table('periods',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('video_num', sa.Integer(), nullable=False),
        sa.Column('country_id', sa.String(), nullable=False),
        sa.Column('begin_year', sa.Integer(), nullable=False),
        sa.Column('end_year', sa.Integer(), nullable=False),
        sa.Column('is_main', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
        sa.ForeignKeyConstraint(['video_num'], ['videos.num'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transformations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('before_id', sa.String(), nullable=False),
        sa.Column('after_id', sa.String(), nullable=False),
        sa.Column('type', sa.Enum('SPLIT', 'MERGE', 'RENAME', 'ANNEXATION', 'INDEPENDENCE', 'TRANSFER', name='transformationtypes'), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['after_id'], ['countries.id'], ),
        sa.ForeignKeyConstraint(['before_id'], ['countries.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transformations')
    op.drop_table('periods')
    op.drop_table('videos')
    op.drop_table('countries')
    # ### end Alembic commands ###
