"""deleted

Revision ID: a72799d56a9d
Revises: 47df0d412c7d
Create Date: 2026-06-15 14:39:01.216410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72799d56a9d'
down_revision: Union[str, Sequence[str], None] = '47df0d412c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('periods', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('transformations', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'deleted')
    op.drop_column('transformations', 'deleted')
    op.drop_column('periods', 'deleted')
    op.drop_column('countries', 'deleted')
    # ### end Alembic commands ###
